name: Build and Release

on:
  push:
    tags:
      - "r*"  # Trigger on tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Intel OneAPI is supported on Linux and Windows
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: true  # Initialize and update submodules

      - name: Set up Intel OneAPI
        uses: intel/setup-oneapi@v1
        with:
          components: intel.oneapi.compiler  # Install the Intel C++ compiler

      - name: Set up build environment (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install make

      - name: Build plugin
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            source /opt/intel/oneapi/setvars.sh
            make CXX=icpx MY_CXXFLAGS="-std=c++14 -O2 -fPIC -fvisibility=hidden -D_GLIBCXX_USE_CXX11_ABI=0 -include cstddef"
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
            make CXX=icx MY_CXXFLAGS="-std:c++14 -O2 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -include cstddef"
          fi

      - name: Package artifacts
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cp vscube.so dist/
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            cp vscube.dll dist/
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscube-${{ matrix.os }}
          path: dist/