name: Build and Release

on:
  push:
    tags:
      - "v*"  # Trigger on tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: true  # Initialize and update submodules

      - name: Set up build environment (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Set up build environment (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install make

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install make
          choco install mingw --version=12.2.0
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Detect compiler
        id: detect_compiler
        run: |
          if g++ --version | grep -q "g++"; then
            echo "COMPILER=gcc" >> $GITHUB_ENV
          else
            echo "COMPILER=clang" >> $GITHUB_ENV
          fi

      - name: Build plugin
        shell: pwsh
        run: |
          if ($env:COMPILER -eq "gcc") {
            $env:MY_CXXFLAGS = "-std=c++14 -O2 -fPIC -fvisibility=hidden -D_GLIBCXX_USE_CXX11_ABI=0 -include cstddef"
          } else {
            $env:MY_CXXFLAGS = "-std=c++14 -O2 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -include cstddef"
          }
          make MY_CXXFLAGS="$env:MY_CXXFLAGS"