name: Build and Release

on:
  push:
    tags:
      - "v*"  # Trigger on tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: true  # Initialize and update submodules

      - name: Set up build environment (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Set up build environment (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install make

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install make

      - name: Build plugin
        run: |
          make

      - name: Package artifacts
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cp vscube.so dist/
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            cp vscube.dylib dist/
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            cp vscube.dll dist/
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscube-${{ matrix.os }}
          path: dist/