name: Build and Release

on:
  push:
    tags:
      - "v*"  # Trigger on tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: true  # Initialize and update submodules

      - name: Set up build environment (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Set up build environment (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install make

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install make
          choco install mingw --version=12.2.0
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Build plugin
        run: |
          if [ "$COMPILER" = "gcc" ]; then
            export MY_CXXFLAGS="-std=c++14 -O2 -fPIC -fvisibility=hidden -D_GLIBCXX_USE_CXX11_ABI=0"
          else
            export MY_CXXFLAGS="-std=c++14 -O2 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0"
          fi
          make MY_CXXFLAGS="$MY_CXXFLAGS"

      - name: Package artifacts
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cp vscube.so dist/
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            cp vscube.dylib dist/
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            cp vscube.dll dist/
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscube-${{ matrix.os }}
          path: dist/